# -*- coding: utf-8 -*-
"""YoloV5 - Drowsiness Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wy-qG1azKltLANns0QBFUWfyWOlnwTLJ
"""

!pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2
from PIL import Image
from google.colab.patches import cv2_imshow

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

img = "/content/teste_4.jpg"

results = model(img)
results.print()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()